apiVersion: v1
kind: Secret

metadata:
  name: easyshop-secrets
  namespace: easyshop

type: Opaque

stringData:

  NEXTAUTH_SECRET: change-me

  JWT_SECRET: change-me

  MONGO_USERNAME: admin

  MONGO_PASSWORD: password123
